name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: CI Test
        run: mvn verify
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: robot.jar 
          path: bin/robot.jar
          retention-days: 90
